[package]
name = "rail-build"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
rail-check = { workspace = true }
rail-diag = { workspace = true }
rail-lower = { workspace = true }
rail-codegen = { workspace = true }

[dev-dependencies]
rail-testkit = { workspace = true }
