//! The skeleton runtime linked into every program `rail` builds: the C `main`
//! entry, `skel.print_i64` and the trap handler.
//!
//! Building block: RuntimeCore (skeleton subset, contract C6/E7). Owning unit:
//! U1 walking-skeleton (thin first version; completed by U6 execution-core).
//!
//! A `no_std` static library with `panic = "abort"`. It uses nothing beyond
//! the platform C library, and from it only `write` and `exit` (BR5.6,
//! NFR5.2). Output is written straight to the file descriptor, so nothing is
//! buffered and everything is written out before the program exits (BR5.7).

#![no_std]
#![deny(clippy::undocumented_unsafe_blocks)]
#![deny(unsafe_op_in_unsafe_fn)]

// SAFETY: these declarations match the C library's `write` and `exit` and the
// generated `rail_entry` (no arguments, returns the tag of main's Result).
unsafe extern "C" {
    fn write(fd: i32, buf: *const u8, count: usize) -> isize;
    fn exit(code: i32) -> !;
    fn rail_entry() -> i64;
}

const STDOUT: i32 = 1;
const STDERR: i32 = 2;

/// Exit code for an unhandled trap (E7).
const TRAP_EXIT: i32 = 70;

/// Writes all of `bytes` to `fd`, giving up on an error (there is nowhere
/// left to report it).
fn write_all(fd: i32, mut bytes: &[u8]) {
    while !bytes.is_empty() {
        // SAFETY: the pointer and length describe the live slice `bytes`.
        let written = unsafe { write(fd, bytes.as_ptr(), bytes.len()) };
        let Ok(written) = usize::try_from(written) else {
            return;
        };
        if written == 0 {
            return;
        }
        bytes = bytes.get(written..).unwrap_or(&[]);
    }
}

fn exit_process(code: i32) -> ! {
    // SAFETY: `exit` ends the process; the runtime holds no state to clean up.
    unsafe { exit(code) }
}

/// `skel.print_i64`: the value in decimal and one LF on standard output.
#[unsafe(no_mangle)]
pub extern "C" fn rail_rt_print_i64(value: i64) {
    let mut buffer = [0u8; 21];
    let mut at = buffer.len();
    at -= 1;
    buffer[at] = b'\n';
    let mut magnitude = value.unsigned_abs();
    loop {
        at -= 1;
        buffer[at] = b'0' + (magnitude % 10) as u8;
        magnitude /= 10;
        if magnitude == 0 {
            break;
        }
    }
    if value < 0 {
        at -= 1;
        buffer[at] = b'-';
    }
    write_all(STDOUT, &buffer[at..]);
}

/// A trap: one line on standard error, then exit code 70 (BR5.3, BR5.4).
#[unsafe(no_mangle)]
pub extern "C" fn rail_rt_trap(kind: i64) -> ! {
    let line: &[u8] = match kind {
        1 => b"trap: integer overflow\n",
        2 => b"trap: division by zero\n",
        _ => b"trap: unknown trap\n",
    };
    write_all(STDERR, line);
    exit_process(TRAP_EXIT)
}

/// The C entry point: runs the rAiL `main` and maps its Result to the exit
/// code (0 for Ok, 1 for Err; E7).
#[unsafe(no_mangle)]
pub extern "C" fn main(_argc: i32, _argv: *const *const u8) -> i32 {
    // SAFETY: `rail_entry` is generated by rail-codegen for the module being
    // built; it takes no arguments and returns 0 (Ok) or 1 (Err).
    let tag = unsafe { rail_entry() };
    if tag == 0 {
        0
    } else {
        write_all(STDERR, b"error: main returned Err\n");
        1
    }
}

#[panic_handler]
fn panic(_: &core::panic::PanicInfo<'_>) -> ! {
    write_all(STDERR, b"trap: runtime panic\n");
    exit_process(TRAP_EXIT)
}
